apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.conainerName }}
          image: "{{ .Values.imageName }}:{{ .Values.imageTag }}"
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST # Setting Database host address from configMap
              value: {{ .Values.DB_HOST }}

            - name: DB_NAME # Setting Database name from configMap
              value: {{ .Values.DB_NAME }}

            - name: DB_USER # Setting Database username from Secret
              value: {{ .Values.DB_USER }}

            - name: DB_PASSWORD # Setting Database password from Secret
              value: {{ .Values.DB_PASSWORD }}