apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}  
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.port }} # The port that the service is running on in the cluster
      targetPort: {{ .Values.targetPort }} # The port exposed by the service
  type: {{ .Values.serviceType }} # type of the service.